### ISSUE TITLE
Alert operators of incomming chat requests in any template page

### ISSUE THREAD

**Issue by mfairchild365** [unl/VisitorChat#3]
We need to alert operators of incoming chat requests when they are set to "available" and viewing any template page.  

All we should have to do is move the alert JavaScript into its own class, have the chatBase class extend the alert class and create a new operatorNotify class.  The as long as the operator is set to "available", the operatorNotify class should constantly ask the server if there are new requests.

**Comment by jsturek** [comment]
old closing
