### ISSUE TITLE
PHP Deprecated:  mysql_escape_string()

### ISSUE THREAD

**Issue by saltybeagle** [unl/VisitorChat#345]
`PHP Deprecated:  mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead. in src/UNL/VisitorChat/Conversation/Record.php on line 292, referer: http://ucommchat.unl.edu/`

**Comment by mfairchild365** [comment]
fixed in https://github.com/unl/VisitorChat/commit/b01f2c2d92bc00e58325bef0b514beecce5663d1 https://github.com/unl/VisitorChat/commit/124ec86d38adc8261e4635e63061e2018e17592c and https://github.com/unl/VisitorChat/commit/fbe5db7c608d6d3eded616baf7c3e6268261fc6c

**Comment by saltybeagle** [comment]
:+1:  Thanks @mfairchild365
