### ISSUE TITLE
Don't hardcode media query width

### ISSUE THREAD

**Issue by ericras** [unl/VisitorChat#362]
https://github.com/unl/VisitorChat/blob/9afc3b7cfaac6aaec3f943c0e4a59f1bcdee91da/www/css/VisitorChat/5.0/client.css#L390

It would be nice if unl/wdntemplates had a "mobile" class applied to the body when in mobile widths.

**Comment by jsturek** [comment]
Since this css comes from unl/wdntemplates `js-src/hover_intent.babel.js`, it's a more of a WDN framework issue. Moving issue to unl/wdntemplates.
