### ISSUE TITLE
Move Operator Chatting options into the templates

### ISSUE THREAD

**Issue by mfairchild365** [unl/VisitorChat#5]
Move the operator chatting options into the templates, such allowing the operator to switch between "Available" and "Busy".  Once this is in the templates, it can be removed from the "Dashboard".  The goal here is to always allow operators to be available for chatting regardless of where they are in the templates.  What we need to decide is where to put these options.

Perhaps two links/options would be best right now.
- Go To Chat Dashboard
- Toggle Availability

**Comment by jsturek** [comment]
old closing
